<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Nias extends Model
{
    protected $table      = 'NIAS_STRUCT';
    protected $primaryKey = 'ID';

    protected $fillable = [
        'user_id',
        'NONIAS','NAMA','GENDER','TGLLAHIR','TEMPATLAHIR','NIK','EMAIL',
        'NAMACLUB','KDCLUB','KDJENIS','JENIS','KDKOTA','NAMAKOTA',
        'KDJENISDOM','JENISDOM','KDPROPDOM','NAMAPROPDOM','KDKOTADOM','NAMAKOTADOM',
        'STATUS','TGLDAFTAR','EXPIRED','LASTMUTASI','MUTASI','TGLDAFTAR_UPDATE',
        'file_kk','file_foto','file_akte','file_ijazah', 'is_update', 'tipe_update',
        'file_sk_mutasi', 'mutasi_luar_jatim',
        'is_sent', 'sent_at',
    ];

    /**
     * Relasi ke pelatih/official yang mendaftarkan
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    protected $casts = [
        'TGLLAHIR'  => 'date',
        'TGLDAFTAR' => 'date',
        'TGLDAFTAR_UPDATE' => 'date',
        'EXPIRED'   => 'date',
        'is_sent' => 'boolean',
        'sent_at' => 'datetime',
    ];

    /**
     * Club lookup — from LOOKUP_CLUB_KOTAKAB in NiasUpdate_MDB.py
     * 'CLUB NAME' => [KDJENIS, JENIS, KDKOTA, NAMAKOTA]
     */
    public static array $clubLookup = [
        'POSSI KAB. BANGKALAN'       => ['1','KAB','35263','BANGKALAN'],
        'CHARLIE DIVING CLUB'        => ['1','KAB','35104','BANYUWANGI'],
        'DOLPHINE DIVING CLUB'       => ['1','KAB','35104','BANYUWANGI'],
        'MUNGSING DIVING CLUB'       => ['1','KAB','35104','BANYUWANGI'],
        'OSING AQUATIC DIVING CLUB'  => ['1','KAB','35104','BANYUWANGI'],
        'SMANTA DIVING CLUB'         => ['1','KAB','35104','BANYUWANGI'],
        'LOTUS AQUATIC CLUB'         => ['0','KOTA','35793','BATU'],
        'PRADAH DC'                  => ['1','KAB','35054','BLITAR'],
        'SAILFISH DC'                => ['1','KAB','35054','BLITAR'],
        'TIRTA KHARISMA DC'          => ['1','KAB','35054','BLITAR'],
        'MARLIN'                     => ['0','KOTA','35723','BLITAR'],
        'POSSI KOTA BLITAR'          => ['0','KOTA','35723','BLITAR'],
        'POSSI KAB. BOJONEGORO'      => ['1','KAB','35224','BOJONEGORO'],
        'BOJONEGORO WATER SPORT'     => ['1','KAB','35224','BOJONEGORO'],
        'POSEIDON DC'                => ['1','KAB','35224','BOJONEGORO'],
        'POSSI KAB. BONDOWOSO'       => ['1','KAB','35112','BONDOWOSO'],
        'PETROKIMIA DC'              => ['1','KAB','35255','GRESIK'],
        'HQL. ALAM'                  => ['1','KAB','35093','JEMBER'],
        'POSSI JEMBER'               => ['1','KAB','35093','JEMBER'],
        'DIAMOND AC'                 => ['1','KAB','35093','JEMBER'],
        'FALCON FINSWIMMING CLUB'    => ['1','KAB','35093','JEMBER'],
        'DEWARUCI'                   => ['1','KAB','35174','JOMBANG'],
        'NAGAPASA DC'                => ['1','KAB','35174','JOMBANG'],
        'GARUDA DC'                  => ['1','KAB','35062','KEDIRI'],
        'MARIO DC'                   => ['1','KAB','35062','KEDIRI'],
        'ANUGRAH DC'                 => ['1','KAB','35062','KEDIRI'],
        'BIMA SAKTI DC'              => ['1','KAB','35062','KEDIRI'],
        'HENS DC'                    => ['1','KAB','35062','KEDIRI'],
        'ARWANA'                     => ['0','KOTA','35715','KEDIRI'],
        'JOYOBOYO'                   => ['0','KOTA','35715','KEDIRI'],
        'SURYA AQUATIC'              => ['0','KOTA','35715','KEDIRI'],
        'DOHO ELS'                   => ['0','KOTA','35715','KEDIRI'],
        'DRAGON AQUATIC'             => ['0','KOTA','35715','KEDIRI'],
        'GALAXY AQUATIC DC'          => ['0','KOTA','35715','KEDIRI'],
        'THUNDER DC'                 => ['0','KOTA','35715','KEDIRI'],
        'POSSI KAB. LAMONGAN'        => ['1','KAB','35247','LAMONGAN'],
        'TIRTA MERU'                 => ['1','KAB','35085','LUMAJANG'],
        'SEA STAR'                   => ['1','KAB','35085','LUMAJANG'],
        'PELANGI DC'                 => ['1','KAB','35085','LUMAJANG'],
        'TUNAS HARAPAN DC'           => ['1','KAB','35085','LUMAJANG'],
        'POSSI KAB. MADIUN'          => ['1','KAB','35197','MADIUN'],
        'PANGERAN TIMOER DC'         => ['1','KAB','35197','MADIUN'],
        'PUSPITA'                    => ['0','KOTA','35777','MADIUN'],
        'MANTARAY'                   => ['0','KOTA','35777','MADIUN'],
        'MARTINA'                    => ['0','KOTA','35777','MADIUN'],
        'LOUHAN MANUNGGAL'           => ['1','KAB','35201','MAGETAN'],
        'CORENA'                     => ['1','KAB','35077','MALANG'],
        'FBA DC'                     => ['1','KAB','35077','MALANG'],
        'GLOBE AQUATIC'              => ['1','KAB','35077','MALANG'],
        'OSCAR DC'                   => ['1','KAB','35077','MALANG'],
        'FASTER BETTER DC'           => ['0','KOTA','35731','MALANG'],
        'AMARTA'                     => ['0','KOTA','35731','MALANG'],
        'CLASS'                      => ['0','KOTA','35731','MALANG'],
        'ORCA'                       => ['0','KOTA','35731','MALANG'],
        'TAMAN HARAPAN'              => ['0','KOTA','35731','MALANG'],
        'TIRTA NIRWANA'              => ['0','KOTA','35731','MALANG'],
        'ARTSEIDON DC'               => ['0','KOTA','35731','MALANG'],
        'TIRTA SANI GEMILANG DC'     => ['0','KOTA','35731','MALANG'],
        'ATLANTIC DC'                => ['1','KAB','35166','MOJOKERTO'],
        'POSSI KOTA MOJOKERTO'       => ['0','KOTA','35762','MOJOKERTO'],
        'SENDANG JAYA TIRTA'         => ['1','KAB','35182','NGANJUK'],
        'TIRTA MULYA'                => ['1','KAB','35182','NGANJUK'],
        'THE LEGEND DC'              => ['1','KAB','35182','NGANJUK'],
        'BRANTAS DC'                 => ['1','KAB','35182','NGANJUK'],
        'POSSI KAB. NGAWI'           => ['1','KAB','35216','NGAWI'],
        'POSSI KAB.PACITAN'          => ['1','KAB','35015','PACITAN'],
        'POSSI KAB.PAMEKASAN'        => ['1','KAB','35286','PAMEKASAN'],
        'PAS SC'                     => ['1','KAB','35143','PASURUAN'],
        'TIGER'                      => ['1','KAB','35143','PASURUAN'],
        'BANYU BIRU'                 => ['1','KAB','35143','PASURUAN'],
        'KKGO DC'                    => ['1','KAB','35143','PASURUAN'],
        'MANDIRI DC'                 => ['1','KAB','35143','PASURUAN'],
        'DRAGO DC'                   => ['1','KAB','35143','PASURUAN'],
        'TIRTA SUROPATI'             => ['1','KAB','35143','PASURUAN'],
        'TIMBUL DC'                  => ['1','KAB','35143','PASURUAN'],
        'SATRIA DHARMA AQUATIC'      => ['1','KAB','35143','PASURUAN'],
        'BAHARI DIVING CLUB'         => ['1','KAB','35143','PASURUAN'],
        'SCKOUT DIVING CLUB'         => ['1','KAB','35023','PONOROGO'],
        'TUNGGUL NAGA DC'            => ['1','KAB','35023','PONOROGO'],
        'PONOROGO DC'                => ['1','KAB','35023','PONOROGO'],
        'WENGKER DC'                 => ['1','KAB','35023','PONOROGO'],
        'DEWARUCI PONOROGO'          => ['1','KAB','35023','PONOROGO'],
        'CATUR DC'                   => ['1','KAB','35023','PONOROGO'],
        'POSSI KAB.PROBOLINGGO'      => ['1','KAB','35135','PROBOLINGGO'],
        'BATRA DC'                   => ['0','KOTA','35746','PROBOLINGGO'],
        'BERLIAN DC'                 => ['0','KOTA','35746','PROBOLINGGO'],
        'BROMO TIRTA'                => ['0','KOTA','35746','PROBOLINGGO'],
        'POSSI KAB.SAMPANG'          => ['1','KAB','35271','SAMPANG'],
        'AVIATION'                   => ['1','KAB','35151','SIDOARJO'],
        'DELTA DC'                   => ['1','KAB','35151','SIDOARJO'],
        'NEMO DC'                    => ['1','KAB','35151','SIDOARJO'],
        'BALURAN DIVING CLUB'        => ['1','KAB','35127','SITUBONDO'],
        'PASIR PUTIH DC'             => ['1','KAB','35127','SITUBONDO'],
        'POSSI KAB. SITUBONDO'       => ['1','KAB','35127','SITUBONDO'],
        'POSSI KAB.SUMENEP'          => ['1','KAB','35294','SUMENEP'],
        'EAGLE DC'                   => ['0','KOTA','35785','SURABAYA'],
        'HIU'                        => ['0','KOTA','35785','SURABAYA'],
        'POR SURYANAGA'              => ['0','KOTA','35785','SURABAYA'],
        'SBAC'                       => ['0','KOTA','35785','SURABAYA'],
        'CATALINA SURABAYA DC'       => ['0','KOTA','35785','SURABAYA'],
        'PRIMUS DC'                  => ['0','KOTA','35785','SURABAYA'],
        'PENGUIN DC'                 => ['0','KOTA','35785','SURABAYA'],
        'KARPIL DC'                  => ['0','KOTA','35785','SURABAYA'],
        'CELONIA DC'                 => ['0','KOTA','35785','SURABAYA'],
        'TODAK DC'                   => ['0','KOTA','35785','SURABAYA'],
        'SDC'                        => ['0','KOTA','35785','SURABAYA'],
        'ELANG DIVING CLUB'          => ['0','KOTA','35785','SURABAYA'],
        'BLUE WHALE'                 => ['0','KOTA','35785','SURABAYA'],
        'JWALITA SUB AQUATIC CLUB'   => ['1','KAB','35031','TRENGGALEK'],
        'LION DC'                    => ['1','KAB','35031','TRENGGALEK'],
        'TIRTA LAWE'                 => ['1','KAB','35232','TUBAN'],
        'SEMEN GRESIK DC'            => ['1','KAB','35232','TUBAN'],
        'BARRACUDA AQUATIC'          => ['1','KAB','35046','TULUNGAGUNG'],
        'STAR LANE INDONESIA'        => ['1','KAB','35046','TULUNGAGUNG'],
        'CROCODILE'                  => ['1','KAB','35046','TULUNGAGUNG'],
    ];

    /**
     * Club code lookup — from LOOKUP_CLUB_CODE in NiasUpdate_MDB.py
     */
    public static array $clubCodeLookup = [
        'POSSI KAB. BANGKALAN'       => '01',
        'CHARLIE DIVING CLUB'        => '01','DOLPHINE DIVING CLUB'      => '02',
        'MUNGSING DIVING CLUB'       => '03','OSING AQUATIC DIVING CLUB' => '04',
        'SMANTA DIVING CLUB'         => '05','LOTUS AQUATIC CLUB'        => '01',
        'MARLIN'                     => '01','PRADAH DC'                 => '02',
        'SAILFISH DC'                => '03','TIRTA KHARISMA DC'         => '04',
        'POSSI KOTA BLITAR'          => '01','POSSI KAB. BOJONEGORO'     => '01',
        'BOJONEGORO WATER SPORT'     => '02','POSEIDON DC'               => '03',
        'POSSI KAB. BONDOWOSO'       => '01','PETROKIMIA DC'             => '01',
        'HQL. ALAM'                  => '01','POSSI JEMBER'              => '02',
        'DIAMOND AC'                 => '03','FALCON FINSWIMMING CLUB'   => '04',
        'DEWARUCI'                   => '01','NAGAPASA DC'               => '02',
        'GARUDA DC'                  => '01','MARIO DC'                  => '02',
        'ANUGRAH DC'                 => '03','BIMA SAKTI DC'             => '04',
        'HENS DC'                    => '05','ARWANA'                    => '01',
        'JOYOBOYO'                   => '02','SURYA AQUATIC'             => '03',
        'DOHO ELS'                   => '04','DRAGON AQUATIC'            => '05',
        'GALAXY AQUATIC DC'          => '06','THUNDER DC'                => '07',
        'POSSI KAB. LAMONGAN'        => '01','TIRTA MERU'                => '01',
        'SEA STAR'                   => '02','PELANGI DC'                => '03',
        'TUNAS HARAPAN DC'           => '04','POSSI KAB. MADIUN'         => '01',
        'PANGERAN TIMOER DC'         => '02','PUSPITA'                   => '01',
        'MANTARAY'                   => '02','MARTINA'                   => '03',
        'LOUHAN MANUNGGAL'           => '01','CORENA'                    => '01',
        'FBA DC'                     => '02','GLOBE AQUATIC'             => '03',
        'OSCAR DC'                   => '04','FASTER BETTER DC'          => '01',
        'AMARTA'                     => '02','CLASS'                     => '03',
        'ORCA'                       => '04','TAMAN HARAPAN'             => '05',
        'TIRTA NIRWANA'              => '06','ARTSEIDON DC'              => '07',
        'TIRTA SANI GEMILANG DC'     => '08','ATLANTIC DC'               => '01',
        'POSSI KOTA MOJOKERTO'       => '01','SENDANG JAYA TIRTA'        => '01',
        'TIRTA MULYA'                => '02','THE LEGEND DC'             => '03',
        'BRANTAS DC'                 => '04','POSSI KAB. NGAWI'          => '01',
        'POSSI KAB.PACITAN'          => '01','POSSI KAB.PAMEKASAN'       => '01',
        'PAS SC'                     => '01','TIGER'                     => '02',
        'BANYU BIRU'                 => '03','KKGO DC'                   => '04',
        'MANDIRI DC'                 => '05','DRAGO DC'                  => '06',
        'TIRTA SUROPATI'             => '01','TIMBUL DC'                 => '02',
        'SATRIA DHARMA AQUATIC'      => '03','BAHARI DIVING CLUB'        => '01',
        'SCKOUT DIVING CLUB'         => '02','TUNGGUL NAGA DC'           => '03',
        'PONOROGO DC'                => '04','WENGKER DC'                => '05',
        'DEWARUCI PONOROGO'          => '06','POSSI KAB.PROBOLINGGO'     => '01',
        'BATRA DC'                   => '01','BROMO TIRTA'               => '02',
        'BERLIAN DC'                 => '03','POSSI KAB.SAMPANG'         => '01',
        'AVIATION'                   => '01','DELTA DC'                  => '02',
        'NEMO DC'                    => '03','BALURAN DIVING CLUB'       => '01',
        'PASIR PUTIH DC'             => '02','POSSI KAB. SITUBONDO'      => '03',
        'POSSI KAB.SUMENEP'          => '01','EAGLE DC'                  => '01',
        'HIU'                        => '02','POR SURYANAGA'             => '03',
        'SBAC'                       => '04','CATALINA SURABAYA DC'      => '05',
        'PRIMUS DC'                  => '06','PENGUIN DC'                => '07',
        'KARPIL DC'                  => '08','CELONIA DC'                => '09',
        'TODAK DC'                   => '10','SDC'                       => '11',
        'ELANG DIVING CLUB'          => '12','BLUE WHALE'                => '13',
        'JWALITA SUB AQUATIC CLUB'   => '01','LION DC'                   => '02',
        'TIRTA LAWE'                 => '01','SEMEN GRESIK DC'           => '02',
        'BARRACUDA AQUATIC'          => '01','STAR LANE INDONESIA'       => '02',
        'CROCODILE'                  => '03',
    ];

    /**
     * All kota/kab Jawa Timur for domisili.
     * 'DISPLAY NAME' => [KDJENISDOM, JENISDOM, KDKOTADOM]
     */
    public static array $domisiliLookup = [
        // Kabupaten
        'KAB. BANGKALAN'    => ['1','KAB','35263'],
        'KAB. BANYUWANGI'   => ['1','KAB','35104'],
        'KAB. BLITAR'       => ['1','KAB','35054'],
        'KAB. BOJONEGORO'   => ['1','KAB','35224'],
        'KAB. BONDOWOSO'    => ['1','KAB','35112'],
        'KAB. GRESIK'       => ['1','KAB','35255'],
        'KAB. JEMBER'       => ['1','KAB','35093'],
        'KAB. JOMBANG'      => ['1','KAB','35174'],
        'KAB. KEDIRI'       => ['1','KAB','35062'],
        'KAB. LAMONGAN'     => ['1','KAB','35247'],
        'KAB. LUMAJANG'     => ['1','KAB','35085'],
        'KAB. MADIUN'       => ['1','KAB','35197'],
        'KAB. MAGETAN'      => ['1','KAB','35201'],
        'KAB. MALANG'       => ['1','KAB','35077'],
        'KAB. MOJOKERTO'    => ['1','KAB','35166'],
        'KAB. NGANJUK'      => ['1','KAB','35182'],
        'KAB. NGAWI'        => ['1','KAB','35216'],
        'KAB. PACITAN'      => ['1','KAB','35015'],
        'KAB. PAMEKASAN'    => ['1','KAB','35286'],
        'KAB. PASURUAN'     => ['1','KAB','35143'],
        'KAB. PONOROGO'     => ['1','KAB','35023'],
        'KAB. PROBOLINGGO'  => ['1','KAB','35135'],
        'KAB. SAMPANG'      => ['1','KAB','35271'],
        'KAB. SIDOARJO'     => ['1','KAB','35151'],
        'KAB. SITUBONDO'    => ['1','KAB','35127'],
        'KAB. SUMENEP'      => ['1','KAB','35294'],
        'KAB. TRENGGALEK'   => ['1','KAB','35031'],
        'KAB. TUBAN'        => ['1','KAB','35232'],
        'KAB. TULUNGAGUNG'  => ['1','KAB','35046'],
        // Kota
        'KOTA BATU'         => ['0','KOTA','35793'],
        'KOTA BLITAR'       => ['0','KOTA','35723'],
        'KOTA KEDIRI'       => ['0','KOTA','35715'],
        'KOTA MADIUN'       => ['0','KOTA','35777'],
        'KOTA MALANG'       => ['0','KOTA','35731'],
        'KOTA MOJOKERTO'    => ['0','KOTA','35762'],
        'KOTA PASURUAN'     => ['0','KOTA','35754'],
        'KOTA PROBOLINGGO'  => ['0','KOTA','35746'],
        'KOTA SURABAYA'     => ['0','KOTA','35785'],
    ];
}
